version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - ../../.env.development
    volumes:
      - cooknow_pg_data:/bitnami/postgresql

volumes:
  cooknow_pg_data: